[build]
command = "npm run build"
publish = "dist"

[functions]
directory = "netlify/functions"

[dev]
publish = ""
command = "vite"
targetPort = 5173
port = 8888

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
