[build]
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
directory = "netlify/functions"
external_node_modules = ["stripe"]
node_bundler = "esbuild"


[dev]
command = "vite"
targetPort = 5173
port = 8888

