[build]
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
directory = "netlify/functions"
external_node_modules = ["stripe"]
node_bundler = "esbuild"


[dev]
command = "vite"
targetPort = 5173
port = 8888

[[headers]]
  for = "/*"
  [headers.values]
  Content-Security-Policy = """
    default-src 'self';
    script-src 'self' https://js.stripe.com https://*.stripe.com https://*.hcaptcha.com;
    frame-src https://js.stripe.com https://*.stripe.com https://*.hcaptcha.com;
    connect-src 'self' https://api.stripe.com https://*.hcaptcha.com;
    img-src 'self' data: https://*.stripe.com https://*.hcaptcha.com;
    style-src 'self' 'unsafe-inline'; 
  """
